services:
  frontend:
    build: ./frontend
    image: rosalesjr/frontend:latest
    ports:
      - "8081:80"

  middleware:
    build: ./middleware
    image: rosalesjr/middleware:latest
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: rosalesjr/backend:latest
    ports:
      - "8080:8080"
