apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: rosalesjr/middleware:latest
        ports:
        - containerPort: 5000
